/**
 * Chat context provider.
 *
 * Reads live context from a static JSON file generated by
 * scripts/refresh-chat-context.sh (queries agency-admin D1).
 *
 * Run the script before build or call POST /api/chat-refresh to
 * re-read the file. Context is cached in memory at runtime.
 */

// Import the static JSON — rebuilt by refresh script before each deploy
import contextData from './chat-context-data.json'

interface TierPricing {
  /** Display label e.g. "Starter" */
  name: string
  /** Price range string e.g. "$750–$1,200" */
  range: string
  /** Typical delivery window e.g. "1–2 weeks" */
  timeline: string
  /** One-sentence scope note e.g. "A polished landing or 3-page site" */
  scope?: string
}

interface Differentiator {
  /** Short headline e.g. "Automated design direction" */
  label: string
  /** One-sentence explanation */
  detail: string
}

interface ContextData {
  summary: {
    activeClients: number
    activeProjects: number
    completedProjects: number
  }
  portfolio: string[]
  currentWork: string[]
  recentGovernance: string[]
  /** Session 2B: tiers + processes + differentiators + stack now live in the
   * bundle so chat personas reference them instead of hardcoding. All optional
   * for back-compat — a stale chat-context-data.json without these fields
   * falls back to the pre-2B prompt shape. */
  tiers?: TierPricing[]
  processes?: {
    website: string
    app: string
  }
  differentiators?: Differentiator[]
  stack?: {
    websites: string
    apps: string
  }
  launchedOn?: string
  updatedAt: string
}

let cachedBlock: string | null = null

export function getLiveContext(): string {
  if (cachedBlock) return cachedBlock

  const data = contextData as ContextData
  cachedBlock = buildContextBlock(data)
  return cachedBlock
}

export function bustCache(): void {
  cachedBlock = null
}

function buildContextBlock(data: ContextData): string {
  const lines: string[] = [
    '\n\n--- LIVE CONTEXT (auto-updated) ---',
    `Last updated: ${data.updatedAt}`,
    `Active clients: ${data.summary.activeClients}`,
    `Active projects: ${data.summary.activeProjects}`,
    `Completed/launched: ${data.summary.completedProjects}`,
  ]

  if (data.portfolio.length > 0) {
    lines.push('\nLive portfolio:')
    data.portfolio.forEach((p) => lines.push(`- ${p}`))
  }

  if (data.currentWork.length > 0) {
    lines.push('\nCurrently working on:')
    data.currentWork.forEach((w) => lines.push(`- ${w}`))
  }

  if (data.recentGovernance.length > 0) {
    lines.push('\nRecent agent governance reviews:')
    data.recentGovernance.forEach((r) => lines.push(`- ${r}`))
  }

  if (data.tiers && data.tiers.length > 0) {
    lines.push('\nService tiers (quote from these; give a range, direct to /get-started for a custom quote):')
    data.tiers.forEach((t) => {
      const scope = t.scope ? ` — ${t.scope}` : ''
      lines.push(`- ${t.name}: ${t.range} (${t.timeline})${scope}`)
    })
  }

  if (data.processes) {
    lines.push('\nProcess:')
    lines.push(`- Websites: ${data.processes.website}`)
    lines.push(`- Apps: ${data.processes.app}`)
  }

  if (data.stack) {
    lines.push('\nStack:')
    lines.push(`- Websites: ${data.stack.websites}`)
    lines.push(`- Apps: ${data.stack.apps}`)
  }

  if (data.differentiators && data.differentiators.length > 0) {
    lines.push('\nDifferentiators (cite these when asked how UWC is different):')
    data.differentiators.forEach((d) => lines.push(`- ${d.label}: ${d.detail}`))
  }

  if (data.launchedOn) {
    lines.push(`\nUWC launched: ${data.launchedOn}`)
  }

  lines.push('--- END LIVE CONTEXT ---')
  return lines.join('\n')
}
